server:
  port: 9020

spring:
  cloud:
    client:
      ipAddress: localhost

    config:
      fail-fast: true
      discovery:
        service-id: happy-security
        enabled: true
      username: admin
      password: admin
  application:
    name: happy-security


  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml
  type-aliases-package: com.huifer.happy.common.entity.po

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}