server:
  port: 9020

spring:
  cloud:
    client:
      ipAddress: localhost
    config:
      fail-fast: true
      discovery:
        service-id: happy-security
        enabled: true
      username: admin
      password: admin
  application:
    name: happy-security
  boot:
    admin:
      client:
        url: "http://localhost:8084"
        username: "admin"
        password: "admin"
        instance:
          prefer-ip: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/default?useAffectedRows=true&useSSL=false
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml
  type-aliases-package: com.huifer.happy.common.entity.po

eureka:
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/
  instance:
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    ip-address: 127.0.0.1
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
ribbon:
  eureka:
    enabled: true