spring:
  redis:
    jedis:
      pool:
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: localhost
    port: 6379
    database: 10
  jackson:
    property-naming-strategy: CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES
    default-property-inclusion: non_null
server:
  port: 9010