spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root



mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml
  type-aliases-package: com.huifer.happy.common.entity.po